name: main

on:
  - push

jobs:
  test:
    name: Test and lint source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 38
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Setup packages
        run: |
          pip install -U pip setuptools wheel
          pip install -r requirements-dev.txt codecov
      - name: Lint
        run: |
          flake8
          mypy
          black --diff src
          black --check src
          isort --diff src
          isort --check src
      - name: Test
        run: |
          pytest --cov --cov-report=xml
      - name: Send coverage to codecov
        run: |
          codecov
