name: main

on:
  - push

jobs:
  lint:
    name: Lint source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install hatch
        run: pip install hatch
      - name: Lint
        run: hatch run lint:check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.8
            3.9
            3.10
            3.11
            3.12
            3.13
            3.14
          allow-prereleases: true
      - name: Install hatch
        run: pip install hatch
      - name: Test
        run: hatch run cov
      - name: Send coverage to codecov
        run: |
          pip install codecov
          codecov
